### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Vladik01-11** [dockfries/infernus#43]
As far as I understand, callbacks are not received

https://github.com/user-attachments/assets/bc41d77b-e3f9-4756-b1ee-08f24f50fde1

the log is from the end of the video:
```
[dev:server] [2024-08-17 21:40:25.753 +0300] ERROR: executing event [name:OnPlayerDisconnect,index:2] error:
[dev:server] [2024-08-17 21:40:25.753 +0300] ERROR: Cannot read properties of undefined (reading 'id')
[dev:server]     err: {
[dev:server]       "type": "TypeError",
[dev:server]       "message": "Cannot read properties of undefined (reading 'id')",
[dev:server]       "stack":
[dev:server]           TypeError: Cannot read properties of undefined (reading 'id')
[dev:server]               at afterEach (C:\Users\Admin\Desktop\TOST\server\node_modules\.pnpm\@infernus+core@0.11.0-beta.11_@types+lodash-es@4.17.12_lodash-es@4.17.21_lodash@4.17.21\node_modules\@infernus\core\dist\bundle.js:1:113042)
[dev:server]               at p (C:\Users\Admin\Desktop\TOST\server\node_modules\.pnpm\@infernus+core@0.11.0-beta.11_@types+lodash-es@4.17.12_lodash-es@4.17.21_lodash@4.17.21\node_modules\@infernus\core\dist\bundle.js:1:2254)
[dev:server]               at Array.<anonymous> (C:\Users\Admin\Desktop\TOST\server\dist\bundle.js:303:10)
[dev:server]               at p (C:\Users\Admin\Desktop\TOST\server\node_modules\.pnpm\@infernus+core@0.11.0-beta.11_@types+lodash-es@4.17.12_lodash-es@4.17.21_lodash@4.17.21\node_modules\@infernus\core\dist\bundle.js:1:2044)
[dev:server]               at Array.<anonymous> (C:\Users\Admin\Desktop\TOST\server\node_modules\.pnpm\@infernus+core@0.11.0-beta.11_@types+lodash-es@4.17.12_lodash-es@4.17.21_lodash@4.17.21\node_modules\@infernus\core\dist\bundle.js:1:115745)
[dev:server]               at p (C:\Users\Admin\Desktop\TOST\server\node_modules\.pnpm\@infernus+core@0.11.0-beta.11_@types+lodash-es@4.17.12_lodash-es@4.17.21_lodash@4.17.21\node_modules\@infernus\core\dist\bundle.js:1:2044)
[dev:server]               at ht (C:\Users\Admin\Desktop\TOST\server\node_modules\.pnpm\@infernus+core@0.11.0-beta.11_@types+lodash-es@4.17.12_lodash-es@4.17.21_lodash@4.17.21\node_modules\@infernus\core\dist\bundle.js:1:2273)
[dev:server]               at i (C:\Users\Admin\Desktop\TOST\server\node_modules\.pnpm\@infernus+core@0.11.0-beta.11_@types+lodash-es@4.17.12_lodash-es@4.17.21_lodash@4.17.21\node_modules\@infernus\core\dist\bundle.js:1:2462)
[dev:server]     }
```

**Comment by dockfries** [comment]
see #42
